select * from pizza_sales

-- Total Revenue

SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM pizza_sales

-- Average Order Value

SELECT SUM(TOTAL_PRICE)/COUNT(DISTINCT(ORDER_ID)) AVG_ORDERED_VALUE FROM pizza_sales

-- Total Pizza’s Sold

SELECT SUM(QUANTITY) AS TOTAL_PIZZA_SOLD FROM pizza_sales

-- Total Order’s

SELECT COUNT(DISTINCT(ORDER_ID)) AS TOTAL_ORDERS FROM pizza_sales

-- Average Pizza per Order

SELECT CAST(SUM(QUANTITY) AS DECIMAL(10,2))/CAST(COUNT(DISTINCT(ORDER_ID)) AS DECIMAL(10,2)) AS AVG_PIZZA_PER_ORDER FROM pizza_sales

-- Daily Trend for Total Orders

SELECT DATENAME(DW,ORDER_DATE) AS ORDER_DAY, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER 
FROM pizza_sales 
GROUP BY DATENAME(DW,ORDER_DATE) 

-- Monthly Trend for Total Orders

SELECT DATENAME(MONTH,ORDER_DATE)AS MONTH_NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER 
FROM pizza_sales
GROUP BY DATENAME(MONTH,ORDER_DATE)
order by 1

-- Percentage of Sales by Pizza Category

SELECT PIZZA_CATEGORY,SUM(TOTAL_PRICE) AS TOTAL_SALES,SUM(TOTAL_PRICE) * 100 /(SELECT SUM(TOTAL_PRICE) FROM pizza_sales) AS PERCENTAGE_TOTAL_SALES
FROM pizza_sales
GROUP BY PIZZA_CATEGORY

-- Percentage of Sales by Pizza size 

SELECT PIZZA_SIZE,SUM(TOTAL_PRICE) AS TOTAL_SALES,CAST(SUM(TOTAL_PRICE) * 100 /
(SELECT SUM(TOTAL_PRICE) FROM pizza_sales) AS DECIMAL (10,2)) AS PERCENTAGE_TOTAL_SALES
FROM pizza_sales
GROUP BY PIZZA_SIZE
ORDER BY 3 DESC

-- Total Pizza’s Sold by Pizza Category

SELECT PIZZA_CATEGORY,COUNT (QUANTITY) AS PIZZA_QUANTITY,CAST(SUM(TOTAL_PRICE)AS DECIMAL (10,2)) AS TOTAL_SALES
FROM pizza_sales
GROUP BY PIZZA_CATEGORY

-- Top 5 Best Sellers by Revenue, Total Quantity and Total Order’s

SELECT TOP 5 PIZZA_NAME,SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM pizza_sales
GROUP BY PIZZA_NAME 
ORDER BY 2 DESC

-- Bottom 5 Best Sellers by Revenue, Total Quantity and Total Order’s

SELECT TOP 5 PIZZA_NAME,SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM pizza_sales
GROUP BY PIZZA_NAME 
ORDER BY 2 